# Generated by Django 5.2.8 on 2025-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('DishId', models.IntegerField(primary_key=True, serialize=False)),
                ('DishName', models.CharField(max_length=50)),
                ('Ingredients', models.TextField()),
                ('Category', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Userid', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=225)),
            ],
        ),
    ]
