# Generated by Django 5.2.8 on 2025-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
