# Generated by Django 5.2.8 on 2025-11-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Items', models.JSONField()),
                ('TotalPrice', models.IntegerField()),
                ('Status', models.CharField(default='Confirmed', max_length=20)),
                ('OrderedTime', models.DateTimeField(auto_now_add=True)),
                ('ExpectedDelivery', models.DateTimeField()),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.users')),
            ],
        ),
    ]
